import "./globals.css";
import "../styles/Cabecalho.css";
import "../styles/Home.css"
import "../styles/cadastro.css"
import "../styles/cameraPage.css"
import "../styles/login.css"
import { Inter } from "next/font/google";
import Cabecalho from "@/components/cabecalho/Cabecalho";
import Rodape from "@/components/rodape/Rodape";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "4ª Entrega - Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="reset">
        <Cabecalho />
          {children}
        <Rodape />
      </body>
    </html>
  );
}