import "./globals.css";
import "../styles/Cabecalho.module.css";
import "../styles/Home.module.css"
import "../styles/cadastro.module.css"
import "../styles/cameraPage.module.css"
import "../styles/login.module.css"
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "4ª Entrega - Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="reset">
        
          {children}
        
      </body>
    </html>
  );
}